### ISSUE TITLE
macos - Steam News buttons floated away

### ISSUE THREAD

**Issue by pztrn** [tkashkin/eOSSteamSkin#5]
Next button in top right corner. I'm on 10.12.6 and rMBP Late 2013 15", just-downloader master.zip.

![default](https://user-images.githubusercontent.com/869402/31054197-f7792a90-a6c6-11e7-86fe-0c637746ab25.png)

**Comment by tkashkin** [comment]
Я хотел выровнять кнопки по центру, но не получилось. Можно расширить заголовок окна и сделать как в главном окне.

**Comment by pztrn** [comment]
А просто если вниз их перенести?

**Comment by tkashkin** [comment]
![2017-10-01 16 13 19](https://user-images.githubusercontent.com/2003017/31054830-a767baa6-a6c3-11e7-8757-d583c11a3297.png)

**Comment by tkashkin** [comment]
Fixed in 34b7a92.
