### ISSUE TITLE
Support Big Picture Mode

### ISSUE THREAD

**Issue by LeandroStanger** [tkashkin/eOSSteamSkin#8]

**Comment by tkashkin** [comment]
What do you mean? Do you want a button to start Big Picture or having it in menu will be enough?

**Comment by LeandroStanger** [comment]
@tkashkin Have A button to start Big Picture

**Comment by LeandroStanger** [comment]
![captura de tela de 2018-07-15 17-58-37](https://user-images.githubusercontent.com/26097419/42738342-ba65e61a-8858-11e8-974c-ce12e4729c46.png)

**Comment by tkashkin** [comment]
@LeandroStanger what do you mean by this screenshot?

Big Picture button is here.

![image](https://user-images.githubusercontent.com/2003017/42738865-da0ca928-8893-11e8-8d31-35f005065e28.png)

**Comment by LeandroStanger** [comment]
@tkashkin Thanks
